import { setRequestLocale, getMessages } from "next-intl/server";
import { NextIntlClientProvider } from "next-intl";
import type { Metadata } from "next";
import { cookies } from "next/headers";
import { Geist, Geist_Mono } from "next/font/google";
import { auth } from "@/auth";
import NavBar from "./NavBar";
import Footer from "./Footer";
import CookieConsentBanner from "../components/consent/CookieConsentBanner";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Jan Hajek - Photography",
    description: "Generated by Tomas Kaiser",
};

type ConsentValue = "accepted" | "rejected" | null;

export default async function LocaleLayout(props: {
    children: React.ReactNode;
    params: Promise<{ locale: string }>;
}) {
    const { locale } = await props.params;

    setRequestLocale(locale);
    const messages = await getMessages();

    const session = await auth();
    const isAdmin =
        !!session?.user &&
        (session.user as { role?: string }).role === "admin";

    const cookieStore = await cookies();
    const rawConsent = cookieStore.get("site_consent_external")?.value;

    const initialConsent: ConsentValue =
        rawConsent === "accepted" || rawConsent === "rejected"
            ? rawConsent
            : null;

    return (
        <div className={`${geistSans.variable} ${geistMono.variable}`}>
            <NextIntlClientProvider locale={locale} messages={messages}>
                <NavBar isAdmin={isAdmin} />
                {props.children}
                <Footer />
                <CookieConsentBanner initialConsent={initialConsent} />
            </NextIntlClientProvider>
        </div>
    );
}